### ISSUE TITLE
Add isWorldLocked and WorldInUseException to API

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#10]
Currently AdvancedSlimePaper is missing some functionalities such isWorldLocked.
Related commit https://github.com/InfernalSuite/AdvancedSlimePaper/commit/f1fd283fb926b84c3f7f8a1d4f0c32f593565f41

**Comment by Owen1212055** [comment]
Implemented in https://github.com/InfernalSuite/AdvancedSlimePaper/commit/229d57bf95e67be164204ae32186efe85604d6fd
please test

**Comment by korallo159** [comment]
See
https://github.com/InfernalSuite/AdvancedSlimePaper/issues/11
https://github.com/InfernalSuite/AdvancedSlimePaper/issues/12
