### ISSUE TITLE
Convert the SWM Plugin to a paper plugin or set remapping attribute

### ISSUE THREAD

**Issue by davidmayr** [InfernalSuite/AdvancedSlimePaper#112]
**Is your feature request related to a problem? Please describe.**
Yes, in paper 1.20.6 non paper-plugins are assumed to not have Mojang mappings. Since the plugin is quite large, it takes about 4 seconds on my server to remap the whole swm plugin. Since my setup makes caching the remap folder quite annoying (since my servers are started from a template) I would benefit from this being implemented.

**Describe the solution you'd like**
If this plugin used paper plugins or set the appropriate attributes https://docs.papermc.io/paper/dev/project-setup#mojang-mappings the server would start 4 seconds faster in the initial run (and in my case in every single server start)

It should have literally 0 downsides for ASP (except that paper plugins are considered experimental and subject to change - but the attribute can be considered if paper plugins are too risky)

**Comment by kyngs** [comment]
I wanted to fix this in #113, unfortunately the cloud command framework still uses spigot mappings. So this won't probably be tackled until they switch to Mojang ones.

**Comment by kyngs** [comment]
I suggest you cache the directory paper uses for the remapped JARs

**Comment by kyngs** [comment]
Sorry for the confusion in my last message, this will be fixed with #113
