### ISSUE TITLE
Shut down the server in a very short time, world is broken

### ISSUE THREAD

**Issue by addpromax** [InfernalSuite/AdvancedSlimePaper#114]
### Minecraft's Version

slimeworldmanager-1.20.4.jar:git-SlimeWorldManager-15981

### Plugin's Version

SuperiorSkyblock2 version 2024.1

### Describe the bug

A part of the world block is missing
![image](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/assets/124496967/b67dc890-f0d3-43e8-bbeb-a3341e11d147)

This is borken

![image](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/assets/124496967/8f249ee2-310d-46ac-8576-fa3bf17a08d9)

This is right

### To Reproduce

Install the latest version 1.20.4 of AWM, superiorskyblock, ssbslimeworlds.
Use '/is create' to create a new world
Close the server in 1min
Reopen the server
Enter the server and find that part of the world block is missing

### Additional Information

https://mclo.gs/8NGyd0m

**Comment by kyngs** [comment]
1.20.4 is no longer supported. Please get the latest build from the development branch.

**Comment by addpromax** [comment]
This server is running AdvancedSlimePaper version 1.20.6-16004-develop@7c72925 (2024-05-28T19:17:31Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Use is version.
But also has this bug

**Comment by addpromax** [comment]
![image](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/124496967/c669c308-8273-4204-afc1-c16b473d0bf1)

**Comment by addpromax** [comment]
This bug fix in This server is running AdvancedSlimePaper version 1.20.6-16042-HEAD@b5c967a (2024-06-11T19:08:09Z)

**Comment by addpromax** [comment]
> Why did you reopen the issue?

Because the SSB slimeworld plugin just broke, I thought it was working properly but it wasn't

**Comment by kyngs** [comment]
How did it broke? Send the logs

**Comment by addpromax** [comment]
> How did it broke? Send the logs

I use "The api-rework branch is not supported nor intended to be used, why are you using it? Obviously, the branch reworks the API, making old plugins incompatible." verison cause broken.

In fact, I used the latest main branch to build, and the block was still damaged.

![image](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/124496967/50315422-5521-413a-9d03-3ff3ea03154d)

**Comment by addpromax** [comment]
[19:08:13 INFO]: [SWM] Loading world island_79bcb93e-fee3-4282-a0d4-a5d3444e3fa6_normal.
[19:08:13 INFO]: [SWM] Applying datafixers for island_79bcb93e-fee3-4282-a0d4-a5d3444e3fa6_normal.
[19:08:13 INFO]: [SWM] World island_79bcb93e-fee3-4282-a0d4-a5d3444e3fa6_normal loaded in 32ms.

Not anything error in logs

**Comment by kyngs** [comment]
Please provide a list of steps to replicate the issue.

**Comment by addpromax** [comment]
Install the latest version 1.20.6 of AWM(last main branch), superiorskyblock（2024.1-b219）, ssbslimeworlds（2024.1）
Use '/is create' to create a new world
Close the server in 1min(short time)
Reopen the server
Enter the server and find that part of the world block is missing

**Comment by addpromax** [comment]
SSBslimeworlds author say this is slimeworld question: https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/51

**Comment by homerek111** [comment]
@kyngs i have the same problem as is described here
I use the lastest succesfull dev build of AdvancedSlimePaper - #16202 at 26 Jul 04:49

**Comment by kyngs** [comment]
Can you verify this still happens on this build? https://ci.infernalsuite.com/viewLog.html?buildId=2539

**Comment by homerek111** [comment]
> Can you verify this still happens on this build? https://ci.infernalsuite.com/viewLog.html?buildId=2539

nope - still happens :/
![obraz](https://github.com/user-attachments/assets/945fb6e0-5858-4f8c-9b0a-eb4d8a502817)
![obraz](https://github.com/user-attachments/assets/e9985d08-80e8-4805-9c62-f82325d29cc5)

```This server is running AdvancedSlimePaper version 1.21.1-16306-develop@9d2c897 (2024-08-31T21:01:54Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-16283-0c68d84 (MC: 1.21.1)```

**Comment by davidmayr** [comment]
Can you please check if this is still an issue with my patch https://github.com/InfernalSuite/AdvancedSlimePaper/pull/145?

You can download it here:
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f364ee99-bef5-4e05-81a8-0bf7b8879670 -> asp-server.jar
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f8e94136-1c85-4fe2-8ff8-e4f665e4d0bc -> plugin.jar

**Comment by kyngs** [comment]
@homerek111

**Comment by homerek111** [comment]
> @homerek111

I wish you fixed that issue 3 months ago when i was trying to use slimepaper - but at that time you didnt give a fck. I had to give up on this as it was bugged all the time - idk if it's fixed. Maybe in the future i will give it a try but for now i don't see a point wasting my time to test it again.

**Comment by kyngs** [comment]
This project is free and open-source, I (or any other contributor) am not paid, I do this in my free time.
You are welcome to hire a developer who will fix this issue. This is not a paid product, you are not entitled to any support whatsoever.

**Comment by homerek111** [comment]
closing the issue as not planned won't make it solved

**Comment by kyngs** [comment]
The issue is stale; if someone can reproduce it in the build David linked, they can reopen the issue.
