### ISSUE TITLE
Sync worlds.yml with the sources

### ISSUE THREAD

**Issue by Miwasak** [InfernalSuite/AdvancedSlimePaper#116]
Hey, it would be nice if the worlds.yml file could be included in the sources chosen (redis, mysql, ...), so that multi-server setups could load the worlds from one server to the other. other without having to add the world to the file manually.

**Comment by kyngs** [comment]
Hi,
the `worlds.yml` file you're referring to is only used by the SWM plugin. It's intended to be a simple utility plugin for basic world manipulation.
If you have a multi-server setup you should utilize the API and load the worlds yourself.
