### ISSUE TITLE
many warns and errors with slimeworlds + superiorskyblock

### ISSUE THREAD

**Issue by homerek111** [InfernalSuite/AdvancedSlimePaper#123]
**Describe the issue**
i use superiorskyblock and there are weired situations happening with slimeworlds - dev of superiorskyblock told me that most of them should be reported here so i will drop it below...

i made some tests and these are my results... there are many weired things happening and it's hard to explain exactly how it works but it must be a little bit buggy...

WEIRED THINGS:
- SOMETIMES worlds from deleted islands are being saved into slime_worlds...
- SOMETIMES worlds are not being saved into slime_worlds on server restart (mostly end/nether - and later they don't work properly if they weren't saved)

EXAMPLE WARN ON SERVER STOP: https://pastebin.com/TVxkm1B9
EXAMPLE WARN ON SAVING ISLAND WORLDS: https://pastebin.com/kFj3hvWn

SOME STEP BY STEP TESTS:

there is something weired happening after deleting normal island....
1. i created island -> after some time it's file in slime_worlds got created (for normal island)
2. i deleted island -> normal island's file got deleted but just after that end's file got created in slime_worlds (end file for island that just got deleted...) - log: https://pastebin.com/DnXti295
(it happens every time and i didnt even create end portal to enter end world)

-------

1. create island
2. just after that delete it with /is delete
3. restart the server
4. island files (normal + end) are being created in slime_worlds file (but island does not exist anymore)

-------

1. create island
2. just after that i go /spawn and restart the server
3. console warn on save https://pastebin.com/Uiet9fq7
4. after restart island exists but it is not possible to teleport there (no safe blocks to teleport) - there is not world file in slime_worlds
(if you stay on island while doing restart world's files are being saved properly)

-------

1. create island
2. make end and nether portals + enter these worlds to create them
3. go /spawn
4. restart the server - log: https://pastebin.com/grsB3k1c
5. after restart only normal world have file in slime_worlds (portals stop working and can't teleport to other worlds of an island - but island thinks nether and end exist) - log: https://pastebin.com/SdPxH1m4
6. after some time these worlds (end/nether) got saved into slime_worlds files but portals still didnt work (even after server restart)
7. after /is delete command only end and nether worlds got deleted from silme_worlds (normal is still there)

-------

1. create island
2. make end and nether portals + enter these worlds to create them
3. go /spawn
4. wait until worlds get saved - WARNS log: https://pastebin.com/Rjkwe2vC
5. i went back there to enter all 3 worlds and then go /spawn
6. restart the server - log: https://pastebin.com/VjNZK4jS
7. after restart nether + normal world created slime_worlds files - BUT THERE IS NO END WORLD FILE...
8. after restart end portal does not work (nether portal works fine)
9. at the end i execute /is delete command while standing on normal island and this console spam happens: https://pastebin.com/5L6neK24 (nether world got deleted from slime_worlds - BUT NORMAL IS STILL THERE...)

some random warns / errors from tests - was just creating / deleting islands + restarting the server sometimes (hard to specify replication steps...):
- https://pastebin.com/FV7wWrnR
- https://pastebin.com/9myY8Y1u
- https://pastebin.com/8AXdTS6S

Overall there are many possibilites to test... different things happen when you:
- restart the server while being on spawn / on the island
- create portals and new worlds for an island - sometimes they work properly sometimes not (after restart)
- delete island while being on the spawn / on the island
- restart the server after creating an island fast / later 
- etc....

**Spigot version**
This server is running AdvancedSlimePaper version 1.21-16202-HEAD@88f6d33 (2024-07-26T04:53:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Plugin version**
    This server is running AdvancedSlimePaper version 1.21-16202-HEAD@88f6d33 (2024-07-26T04:53:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
    SuperiorSkyblock 2024.2-b298
    Oneblock module # 57
    slimeworld module # 19
    slimepaper/plugin (#16202 at 26 Jul 04:49): https://ci.infernalsuite.com/buildConfiguration/AdvancedSlimePaper_Build/2435?buildTab=artifacts#

**How to reproduce**
stop the server

**Comment by kyngs** [comment]
I'm sorry, but this seems like an issue on SSB2's side.
If someone can fix this, I'll be glad, but I cannot replicate it without SSB2
