### ISSUE TITLE
nether world for skyblock island was not saved properly and after server restart it does not work

### ISSUE THREAD

**Issue by homerek111** [InfernalSuite/AdvancedSlimePaper#125]
**Describe the issue**
as title says...
logs:
1. save failed on closing server https://pastebin.com/PC69Ynbx
2. error on world load (after player joins the server) https://pastebin.com/FYsw8pvr
**Spigot version**
This server is running AdvancedSlimePaper version 1.21-16234-main@99d826f (2024-08-11T20:18:54Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
**Plugin version**
#16234 at 11 Aug 20:16
**How to reproduce**
create island + nether portal -> enter nether -> restart server

**Comment by kyngs** [comment]
Can you verify this still happens on this build? https://ci.infernalsuite.com/viewLog.html?buildId=2539

**Comment by homerek111** [comment]
> Can you verify this still happens on this build? https://ci.infernalsuite.com/viewLog.html?buildId=2539

seems to be working fine.

Tested with:
```
This server is running AdvancedSlimePaper version 1.21.1-16306-develop@9d2c897 (2024-08-31T21:01:54Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-16283-0c68d84 (MC: 1.21.1)
```
SuperiorSkyblock2 2024.3-b317
OneBlock module # 60
Slimeworlds module # 25
