### ISSUE TITLE
ASP removes basic bukkit methods and classes

### ISSUE THREAD

**Issue by Lukadcf** [InfernalSuite/AdvancedSlimePaper#126]
**Describe the issue**
Using the AdvancedSlimePaper jar completely removes the [DamageType](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/damage/DamageType.html) class and Paper's [Entity#isInvisible](https://jd.papermc.io/paper/1.21.1/org/bukkit/entity/Entity.html#isInvisible()) method

**Spigot version**
1.20.4

**Plugin version**
1.20.4-R0.1

**How to reproduce**
Use these classes in a plugin

**Crash reports (if available)**
Failed to register events for class because org/bukkit/damage/DamageType does not exist.

java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.Entity.isInvisible()

**Comment by kyngs** [comment]
1.20.4 is not supported
