### ISSUE TITLE
animal Animals summoned in the SlimeWorld disappear

### ISSUE THREAD

**Issue by minhyeok1202** [InfernalSuite/AdvancedSlimePaper#130]
When I summon animals like cows, chickens, and pigs, and then move to another world, the animals disappear.

On the other hand, monsters like zombies and skeletons are saved.

Is there a solution to this?

https://github.com/user-attachments/assets/811c28ce-3634-4a09-a40a-c59913e4c8e3

I have set SlimeProperties.ALLOW_ANIMALS to true when creating the world.

swm version: 2.10.0
minecraft: 1.20.4

**Comment by kyngs** [comment]
Does this happen on the latest build? https://ci.infernalsuite.com/viewLog.html?buildId=2516

**Comment by davidmayr** [comment]
Can you please check if this is still an issue with my patch https://github.com/InfernalSuite/AdvancedSlimePaper/pull/145?

You can download it here:
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f364ee99-bef5-4e05-81a8-0bf7b8879670 -> asp-server.jar
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f8e94136-1c85-4fe2-8ff8-e4f665e4d0bc -> plugin.jar

**Comment by kyngs** [comment]
Stale, reopen if still occurring.
