### ISSUE TITLE
ASP Memory leak

### ISSUE THREAD

**Issue by ManseDK** [InfernalSuite/AdvancedSlimePaper#144]
I ran a heapdump and there was a big memory leak from asp
![image](https://github.com/user-attachments/assets/ed399dff-2812-4225-8748-9576a816c9b9)

**Spigot version**
1.21.1

**Plugin version**
3.0.0

**How to reproduce**
Starting my server and waiting

**Crash reports (if available)**
It doesn't crash just starts laggin out

**Comment by minhyeok1202** [comment]
Are you perhaps referencing SlimeChunkSkeleton somewhere?

I'm experiencing an issue where Bukkit entities are being referenced in ModelEngine, causing memory to be retained even after the world is unloaded.
