### ISSUE TITLE
Lock is not removed on world unload

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#18]
**Describe the issue**
Lock is not removed on world unload
**Spigot version**
build id c4e6d4
**Plugin version**
build id c4e6d4
**How to reproduce**
1.Load world.
2. Unload world.
3. Check for lock (it's not set to 0)

**Expected behavior**
Lock is removed on world unload.

**Comment by Owen1212055** [comment]
Fixed in https://github.com/InfernalSuite/AdvancedSlimePaper/commit/61148080ba43c722ad9dfc30cf9fb32af1594037
