### ISSUE TITLE
Massive RAM leak & CPU consumption (basically corrupting Slime files)

### ISSUE THREAD

**Issue by Kenuux** [InfernalSuite/AdvancedSlimePaper#2]
**Describe the issue**

Strangely enough, the slime worlds consume more and more RAM (and CPU) with every unload or load. Here is a video where the whole thing is portrayed: https://www.youtube.com/watch?v=AaS2xlszLoE

In the attachments you can find the slime file before the "corruption" and after the "corruption".

Before: [test2.slime.zip](https://github.com/InfernalSuite/AdvancedSlimePaper/files/10332902/test2.slime.zip)
After: [test2_corrupt.slime.zip](https://github.com/InfernalSuite/AdvancedSlimePaper/files/10332916/test2_corrupt.slime.zip)

**Spigot version**
SlimeWorldManager git-SlimeWorldManager-"bb46405" (1.19.3)

**Plugin version**
2.10.0

**How to reproduce**
Just unload and load a slime world minimum 2-5 times and you should be able to reproduce it.

**Crash reports (if available)**
No crash reports available, but here is the entire server log: [latest.log](https://github.com/InfernalSuite/AdvancedSlimePaper/files/10332899/latest.log)

**Comment by Owen1212055** [comment]
Fixed in https://github.com/InfernalSuite/AdvancedSlimePaper/commit/6be7ed66d53d128da59b83a621bf228283b8598e
