### ISSUE TITLE
Slime world is not saved to datasource after being loaded from clone.

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#22]
**Describe the issue**
Slime world is not saved to datasource after being loaded from clone.
**Spigot version**
Latest SlimePaper
**Plugin version**
Latest Plugin
**How to reproduce**

1. Clone slime world.
 clonedWorld= this.defaultWorld.clone("new_world_name", slimeLoader);

2. Load new world.

 slimePlugin.loadWorld(clonedWorld);
 
 3. World is not set in database, also there is missing debug in console (see attached screen which debug is missing)
 
![image](https://user-images.githubusercontent.com/53827110/211159092-1f275da5-8524-49cc-9e85-a44b6374c2d2.png)

**Crash reports (if available)**
If I want to check for example lock on this newly created world, it throws UnknownWorldException

**Expected behavior**
World is loaded like with /swm create <world>, functions like isLocked() and so on, don't throw UnknownWorldException.

**Comment by Owen1212055** [comment]
Interesting, so did this previously ALSO save the world?

**Comment by korallo159** [comment]
@Owen1212055 yes, it was immediately saved in datasource

**Comment by korallo159** [comment]
I will investigate further

**Comment by korallo159** [comment]
@Owen1212055 I don't recall that it was saved in game (atleast SaveWorldEvent was not called) it was saved in datasource immadetialy for sure.
