### ISSUE TITLE
Entities are not imported

### ISSUE THREAD

**Issue by Kenuux** [InfernalSuite/AdvancedSlimePaper#4]
**Describe the issue**
No entities are imported with /swm import.

**Spigot version**

This server is running SlimeWorldManager version git-SlimeWorldManager-"028b3e6" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 028b3e6)

Previous version: git-SlimeWorldManager-"6be7ed6" (MC: 1.19.3)

**Plugin version**
2.10.0

**How to reproduce**
Use /swm import on a world with entities

**Crash reports (if available)**
/

**Comment by Owen1212055** [comment]
Fixed by https://github.com/InfernalSuite/AdvancedSlimePaper/commit/edd8a4de9b8c81d0504bc7cd2f8f7a3372ac8933
