### ISSUE TITLE
Read only world is saved.

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#40]
**Describe the issue**
Read only world is saved. In my case it was tested with API.

**Spigot version**
Latest
**Plugin version**
Latest
**How to reproduce**
Load world
![image](https://user-images.githubusercontent.com/53827110/215597512-b356e9d6-ce6c-4599-a6f1-3c4586afdf85.png)

World is saved, even if read only is true.
![image](https://user-images.githubusercontent.com/53827110/215598093-b71eae21-35e3-4a42-a0bd-c62fbcd407cf.png)

**Notice also my debug**: "Save strategy" is not null, instead it's my datasource value.

**Crash reports (if available)**

**Comment by Owen1212055** [comment]
For information, the way that read only is now done is by setting the loader to null.
https://github.com/InfernalSuite/AdvancedSlimePaper/blob/a90c1d62c4203bcf1e42dd8cf3913d9d62b19c11/plugin/src/main/java/com/grinderwolf/swm/plugin/SWMPlugin.java#L251

Generally this may cause some issues with cloning, so may be reverted.
