### ISSUE TITLE
Provide a pure API that can be packaged into other plugins

### ISSUE THREAD

**Issue by xiaozhangup** [InfernalSuite/AdvancedSlimePaper#43]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
just like https://github.com/GedStudio/Genshin-Craft-Lib-Slime-World-Manager

and the worlddata can store in data source，not in worlds.yml

**Comment by KabanFriends** [comment]
I agree to this suggestion, separating the plugin and the API would be quite helpful
I wanted to make a custom command to load a slime world (along with some specific settings that's unrelated with slime worlds) without having to add default-provided /swm load command in the server

**Comment by Paul19988** [comment]
This is Advanced Slime Paper & not our original ASWM, it functions differently & the plugin is a required counterpart.

**Comment by kyngs** [comment]
As Paul already mentioned, this is not possible with the current structure. Closing as wontfix
