### ISSUE TITLE
Memory leak when not loading worlds

### ISSUE THREAD

**Issue by davidmayr** [InfernalSuite/AdvancedSlimePaper#49]
**Describe the issue**
When slime worlds are fetched from a source but not actually loaded as a bukkit world, they are kept in a map forever. In my case I load worlds from a template and then **clone** them. I only ever load the cloned version, but the template is still being keep in memory. 

**Spigot and Plugin version**
I'm on commit e19b8ff, but the issue still exists after the 1.19.4 commit

**How to reproduce**
Load a world with SlimePlugin#loadWorld(SlimeLoader, String, boolean, SlimePropertyMap) and then do absolutely nothing.
(The same applies to createEmptyWorld as well)

**Crash reports (if available)**
None

**Comment by kyngs** [comment]
This has been resolved by #108 
Currently it's in develop, but it's going to be merged into main soon.
