### ISSUE TITLE
Store chunk persistent data container

### ISSUE THREAD

**Issue by MenschenToaster** [InfernalSuite/AdvancedSlimePaper#57]
**Is your feature request related to a problem? Please describe.**
The chunk's persistent data container is sadly not serialized in slime worlds. 

**Describe the solution you'd like**
In a future slime file version, a new field could be added where the persistent NBT data is stored in.

As a workaround, I currently store the persistent data container in the world's extra tag (Via a compound tag called "chunk_pdc" that stores byte array tags. The key for the array tags is the chunk's chunkKey converted to a string) on chunk/world save (and plugin unload) and load it on chunk load. It seems quite hacky, but it works. Maybe this could be added in ASP itself like I did myself instead of adding a new field?

**Comment by kyngs** [comment]
Implemented in #91
