### ISSUE TITLE
Expected poi chunk to be loaded with chunk

### ISSUE THREAD

**Issue by devilExE3** [InfernalSuite/AdvancedSlimePaper#67]
**Describe the issue**
```
[ChunkDataLoadTask] Expected poi chunk to be loaded with chunk for task com.infernalsuite.aswm.level.ChunkDataLoadTask@11429165
```
gets spammed in the console

**Spigot version**
slimeworldmanager-paperclip-1.20-R0.1-SNAPSHOT-reobf ([aae15c](https://github.com/InfernalSuite/AdvancedSlimePaper/commit/aae15cc5bcc8d2224b85a0649f0c2e34bbcf3330))

**Plugin version**
v2.10.0 ([aae15c](https://github.com/InfernalSuite/AdvancedSlimePaper/commit/aae15cc5bcc8d2224b85a0649f0c2e34bbcf3330))

**How to reproduce**
create a world using `/swm create void file`
go to the world with `/swm goto void`

**Crash reports (if available)**
error doesn't crash the server

**Comment by kyngs** [comment]
> **Describe the issue**
> 
> ```
> [ChunkDataLoadTask] Expected poi chunk to be loaded with chunk for task com.infernalsuite.aswm.level.ChunkDataLoadTask@11429165
> ```
> 
> gets spammed in the console
> 
> **Spigot version** slimeworldmanager-paperclip-1.20-R0.1-SNAPSHOT-reobf ([aae15c](https://github.com/InfernalSuite/AdvancedSlimePaper/commit/aae15cc5bcc8d2224b85a0649f0c2e34bbcf3330))
> 
> **Plugin version** v2.10.0 ([aae15c](https://github.com/InfernalSuite/AdvancedSlimePaper/commit/aae15cc5bcc8d2224b85a0649f0c2e34bbcf3330))
> 
> **How to reproduce** create a world using `/swm create void file` go to the world with `/swm goto void`
> 
> **Crash reports (if available)** error doesn't crash the server

Can you verify this still happens?

**Comment by kyngs** [comment]
Not reproducible and stale.
