### ISSUE TITLE
Player kick/Player quit event is not being called during server disable.

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#68]
**Describe the issue**
Player kick/Player quit event is not being called during disable.
**Spigot version**
latest
**Plugin version**
latest
**How to reproduce**
1. Listen to Quit, kick event in your plugin, add some debugs.
2. Stop server gracefully
3. Debug messages are not shown (event not being called)
**Crash reports (if available)**

**Comment by kyngs** [comment]
This is a feature of Spigot/Paper, not a bug. 
You should utilize the `onDisable` method in your plugin's main class. 
See: https://www.spigotmc.org/threads/is-playerquitevent-called-when-stop-is-used.269901/ for some reference.
