### ISSUE TITLE
Skeleton clone not looping through SlimeChunkSection's correctly 

### ISSUE THREAD

**Issue by ThatForkyDev** [InfernalSuite/AdvancedSlimePaper#70]
**Describe the issue**
Cloning worlds other than an overworld doesn't seem to work, tried NETHER and THE_END, and both result in the same problem being thrown

https://paste.tridentgames.net/uhuvepuwib.md

**Spigot version**
1.20.1 (https://discord.com/channels/741733106930810950/741741550383398942/1133799086861062226)

**Plugin version**
https://discord.com/channels/741733106930810950/741741550383398942/1133799086861062226

**How to reproduce**
/swm clone-world tesing_nether nether_test mongodb

**Crash reports (if available)**

Nether file (before migrating):
- https://cdn.tridentgames.net/u/NMYjGG.slime

worlds conf:
    testing_nether:
        source: mongodb
        spawn: 0, 128, 0
        difficulty: peaceful
        allowMonsters: true
        allowAnimals: true
        dragonBattle: false
        pvp: true
        environment: nether
        worldType: DEFAULT
        defaultBiome: minecraft:crimson_forest
        loadOnStartup: true
        readOnly: false

**Comment by kyngs** [comment]
I can't replicate this on 1.20.4.

@ThatForkyDev Can you please verify that this issue is still relevant on the latest build of develop?

**Comment by kyngs** [comment]
Stale
