### ISSUE TITLE
Gamerules of world not getting saved

### ISSUE THREAD

**Issue by CerialPvP** [InfernalSuite/AdvancedSlimePaper#75]
**Describe the issue**
Basically, if you set gamerules for the world, it does not save, even with /save-all.

**Spigot version**
1.20.1 (Build from September 14th)

**Plugin version**
2.10.0

**How to reproduce**
Just apply a gamerule (like doDaylightCycle), restart the server, and boom.

**Crash reports (if available)**

**Comment by Askarionn** [comment]
it's not a bug, aswm doesn't save gamerules

**Comment by kyngs** [comment]
This is a feature, not a bug.

Duplicate of #45
