### ISSUE TITLE
Fix wiki and use as real github wiki's

### ISSUE THREAD

**Issue by Elikill58** [InfernalSuite/AdvancedSlimePaper#77]
Actually, the readme.md as 404 link and use direct file in the repo for the wiki. But, github as a feature to have a wiki directly included on the repo (the url would be https://github.com/InfernalSuite/AdvancedSlimePaper/wiki).

Can you do this and update the wiki with new things? For example the doc said to use `setInt` but it's a deprecated method...

**Comment by kyngs** [comment]
The issue with GH Wiki is, that it requires repo write access to contribute to it.
I think we should keep it in the format of MD files and just rather update it.

**Comment by Elikill58** [comment]
You are right. But, the community doesn't know how the code is made, which method used etc. That's why, most of repo use GH wiki. Only the global readme is ok the repo itself.

Else, I understand if you really don't want to use GH wiki.

**Comment by kyngs** [comment]
We're planning to use a different wiki solution than GH wiki.
I can't give any ETA on when that happens tho. It'll hopefully be more readable than the current one.
