### ISSUE TITLE
Empty worlds with schematics pasted inside of them don't save

### ISSUE THREAD

**Issue by vopswtf** [InfernalSuite/AdvancedSlimePaper#87]
When an empty world is created and a WorldEdit schematic is pasted into it (via API), the world is fine.

But once the world is cloned, it is empty and is missing the schematic.

![image](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/55073114/7e4f84dc-6404-435f-9870-7a3b48a03854)

Discussed in discord
https://discord.com/channels/741733106930810950/1146862190440218624/1171926146166829166

NOTE:
Title is old, issue with saving was an error on my side. But the cloning still consists of an empty map.

**Comment by kyngs** [comment]
Possibly related to #84 ?

**Comment by vopswtf** [comment]
I thought I should reiterate that the schematic does appear in the world once it is reloaded (either by restarting or using Bukkit.unloadWorld

**Comment by vopswtf** [comment]
> Just a sanity check: Did you save the world before cloning it? If yes, can you still replicate this on the latest build from the "develop" branch?

Yes, and my currently implementation already uses the latest branch (but automatically reloads the world from prior dev ver)
I'll try again without unloading the worlds later.

**Comment by kyngs** [comment]
Can you verify this still happens on this build? https://ci.infernalsuite.com/viewLog.html?buildId=2539

**Comment by davidmayr** [comment]
Can you please check if this is still an issue with my patch #145? 

You can download it here:
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f364ee99-bef5-4e05-81a8-0bf7b8879670 -> asp-server.jar
https://api.infernalsuite.com/v1/projects/asp/9ec6c7f1-5e48-44c0-a87f-7007ccef6ae0/download/f8e94136-1c85-4fe2-8ff8-e4f665e4d0bc -> plugin.jar
