### ISSUE TITLE
No class def found error when using SWM API.

### ISSUE THREAD

**Issue by korallo159** [InfernalSuite/AdvancedSlimePaper#9]
**Describe the issue**

[00:49:05 ERROR]: Error occurred while enabling  ***... (Is it up to date?)
java.lang.NoClassDefFoundError: com.grinderwolf.swm.api.exceptions.UnknownWorldException

**Spigot version**
slimeworldmanager-paperclip-1.19.3-R0.1-SNAPSHOT-reobf.jar
**Plugin version**
plugin-1.19.3-R0.1-SNAPSHOT.jar
**How to reproduce**
Use SlimeWorldManager API in your plugin.

<groupId>com.grinderwolf</groupId>
            <artifactId>slimeworldmanager-api</artifactId>
            <version>2.10.0-SNAPSHOT</version>
            <scope>provided</scope>
            
<repositories>
  <repository>
    <id>rapture-snapshots</id>
    <url>https://repo.rapture.pw/repository/maven-snapshots/</url>
  </repository>
</repositories>

**Comment by Kenuux** [comment]
Looks like the packages have been renamed. For now you would have to build the `api` module and install it into your local Maven repo until the official repo is set up.

Before: `com.grinderwolf.swm.api.exceptions.UnknownWorldException`
After: `com.infernalsuite.aswm.exceptions.UnknownWorldException`

Kind of like this:
```
mvn install:install-file \
   -Dfile=api-1.19.3-R0.1-SNAPSHOT.jar \
   -DgroupId=com.infernalsuite.aswm \
   -DartifactId=api \
   -Dversion=1.19.3-R0.1-SNAPSHOT \
   -Dpackaging=jar \
   -DgeneratePom=true
```
Then you depend on it as such: 
```
    <dependency>
      <groupId>com.infernalsuite.aswm</groupId>
      <artifactId>api</artifactId>
      <version>1.19.3-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
``` 
I guess that would be an easy quick fix.

**Comment by Owen1212055** [comment]
Correct, you need to make sure to use the new API artifact, as we have renamed it under this organization.  
We will have new artifacts up *soon*
