### ISSUE TITLE
Worlds are not upgrading correctly from 1.20.1 -> 1.20.4

### ISSUE THREAD

**Issue by TheDeafCreeper** [InfernalSuite/AdvancedSlimePaper#94]
**Describe the issue**
When upgrading a world from 1.20.1 -> 1.20.4 the world ends up empty instead of containing the correct chunk data.

Logs do not indicate any issues
```
[05:21:50] [Server thread/INFO]: TheDeafCreeper issued server command: /swm load Hub
[05:21:50] [Craft Scheduler Thread - 11 - SlimeWorldManager/INFO]: [SWM] Loading world Hub.
[05:21:51] [Craft Scheduler Thread - 11 - SlimeWorldManager/INFO]: [SWM] Applying datafixers for Hub.
[05:21:53] [Craft Scheduler Thread - 11 - SlimeWorldManager/INFO]: [SWM] World Hub loaded in 2146ms.
[05:21:55] [Server thread/INFO]: TheDeafCreeper issued server command: /swm goto Hub
```

An earlier 1.20.4 build (I'm not sure which, every version I've tried so far failed, it was before the arrow fix  though) did successfully convert worlds, and the updated worlds are correctly loaded on the current 1.20.4 server if already converted.

**Spigot version**
1.20.1 Server [`SlimeWorldManager-15169` (MC: 1.20.1), Git `191c7b2` on paper_upstream]
1.20.4 Server [`SlimeWorldManager-15616` (MC: 1.20.4), Git: `b8f20c5` on paper_upstream]

**Plugin version**
1.20.1 Plugin [2.10.0]
1.20.4 Plugin [2.10.0]

**How to reproduce**
Create a world using `SlimeWorldManager-15169`, then try to update to 1.20.4, the world should lose all it's chunk data.

**Crash reports (if available)**

**Comment by TheDeafCreeper** [comment]
Actually I think this is related to https://discord.com/channels/741733106930810950/1185354365205229698
I tried another world and got this:
![2023-12-29_23 41 32](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/34897909/7b6da820-6d48-4685-a7a1-dc36566284c5)

**Comment by kyngs** [comment]
We're aware, this is going to be fixed by the v12 PR (#91)

**Comment by kyngs** [comment]
@TheDeafCreeper The PR has been merged, can you please obtain the latest develop build and test whether this still occurs?

**Comment by kyngs** [comment]
Stale, probably fixed
